services:
    scratcha_server:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: scratcha_server
        env_file:
            - ./.env
        ports:
            - "8001:8001"
        environment:
            - TZ=Asia/Seoul
        volumes:
            - ./app:/app/app
            - ./alembic:/app/alembic
            - ./alembic.ini:/app/alembic.ini
        depends_on:
            db:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

    # MySQL 데이터베이스 서비스
    db:
        image: mysql:8.0
        container_name: scratcha_db
        env_file:
            - ./.env
        ports:
            - "3306:3306"
        environment:
            - TZ=Asia/Seoul
        volumes:
            - scratcha_volume_local:/var/lib/mysql
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD"]
            timeout: 20s
            retries: 10
            interval: 3s
            start_period: 30s

    # RabbitMQ 서비스
    rabbitmq:
        image: rabbitmq:3.13-management
        container_name: scratcha_rabbitmq
        env_file:
            - ./.env
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
        ports:
            - "5672:5672" # AMQP port
            - "15672:15672" # Management UI port
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq/
        healthcheck:
            test: ["CMD", "rabbitmq-diagnostics", "ping"]
            interval: 30s
            timeout: 30s
            retries: 3

    # Celery 워커 서비스
    celery_worker:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: scratcha_worker
        env_file:
            - ./.env
        environment:
            - TZ=Asia/Seoul
        volumes:
            - ./app:/app/app
            - ./alembic:/app/alembic
            - ./alembic.ini:/app/alembic.ini
        depends_on:
            db:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        command: ["celery", "-A", "app.celery_app", "worker", "--loglevel=info"]

    # Celery Beat 서비스 (주기적 작업 스케줄러)
    celery-beat:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: scratcha_celery_beat
        env_file:
            - ./.env
        volumes:
            - ./app:/app/app
        depends_on:
            db:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        command: ["celery", "-A", "app.celery_app", "beat", "--loglevel=info"]

# Docker 볼륨 정의
volumes:
    scratcha_volume_local:
    rabbitmq_data:
