"""Add is_correct column to captcha_log manually

Revision ID: 04f3acc7b179
Revises: 979c61390010
Create Date: 2025-09-12 16:50:37.097116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f3acc7b179'
down_revision: Union[str, Sequence[str], None] = '979c61390010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('captcha_log', sa.Column('is_correct', sa.Boolean(), nullable=True, comment='캡챠 문제 정답 여부 (True: 정답, False: 오답)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('captcha_log', 'is_correct')
    # ### end Alembic commands ###