"""Add ondelete cascade to captcha_session

Revision ID: 19536121bb8f
Revises: 83a71340fd40
Create Date: 2025-09-03 11:26:40.270036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19536121bb8f'
down_revision: Union[str, Sequence[str], None] = '83a71340fd40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('captcha_session_ibfk_1', 'captcha_session', type_='foreignkey')
    op.create_foreign_key(None, 'captcha_session', 'api_key', ['api_key_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'captcha_session', type_='foreignkey')
    op.create_foreign_key('captcha_session_ibfk_1', 'captcha_session', 'api_key', ['api_key_id'], ['id'])
    # ### end Alembic commands ###
