"""Normalize captcha user info, move ip and user_agent to session

Revision ID: 373946e1c8b1
Revises: 552c401be985
Create Date: 2025-09-01 13:24:14.887670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '373946e1c8b1'
down_revision: Union[str, Sequence[str], None] = '552c401be985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('captcha_log', 'user_agent')
    op.drop_column('captcha_log', 'ip_address')
    op.add_column('captcha_session', sa.Column('ip_address', sa.String(length=50), nullable=True, comment='사용자 IP 주소'))
    op.add_column('captcha_session', sa.Column('user_agent', sa.String(length=255), nullable=True, comment='사용자 User-Agent'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('captcha_session', 'user_agent')
    op.drop_column('captcha_session', 'ip_address')
    op.add_column('captcha_log', sa.Column('ip_address', mysql.VARCHAR(length=45), nullable=True, comment='요청자 IP'))
    op.add_column('captcha_log', sa.Column('user_agent', mysql.TEXT(), nullable=True, comment='요청자 브라우저 정보'))
    # ### end Alembic commands ###
