"""delete description_plan column of user table

Revision ID: 51aeaed07084
Revises: d7e9d1811c97
Create Date: 2025-09-01 10:09:24.962161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '51aeaed07084'
down_revision: Union[str, Sequence[str], None] = 'd7e9d1811c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_key', 'expires_at',
               existing_type=mysql.DATETIME(),
               comment='만료 시각 : 0 >= 무제한, 1=1일, 7=7일, 30=30일 등',
               existing_nullable=True)
    op.alter_column('api_key', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='생성 시각',
               existing_nullable=False)
    op.alter_column('api_key', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='수정 시각',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('api_key', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment='삭제 시각 (soft-delete)',
               existing_nullable=True)
    op.alter_column('application', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='생성 시각',
               existing_nullable=False)
    op.alter_column('application', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='수정 시각',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('application', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment='삭제 시각 (soft-delete)',
               existing_nullable=True)
    op.alter_column('captcha_log', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='문제 생성 시간',
               existing_nullable=False)
    op.alter_column('captcha_problem', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='문제 생성 시각',
               existing_nullable=False)
    op.alter_column('captcha_problem', 'expires_at',
               existing_type=mysql.DATETIME(),
               comment='문제 교체 시각 (만료일)',
               existing_nullable=False)
    op.alter_column('captcha_session', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='생성 시각',
               existing_nullable=False)
    op.alter_column('usage_stats', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='레코드 생성 시각 (기본값으로 현재 시각 사용)',
               existing_nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='생성 시각',
               existing_nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='수정 시각',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('user', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment='삭제 시각 (soft-delete)',
               existing_nullable=True)
    op.drop_column('user', 'subscription_plan')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscription_plan', mysql.ENUM('FREE', 'STARTER', 'PRO', 'ENTERPRISE'), nullable=False, comment='구독한 플랜'))
    op.alter_column('user', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='삭제 시각 (soft-delete)',
               existing_nullable=True)
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='수정 시각',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='생성 시각',
               existing_nullable=False)
    op.alter_column('usage_stats', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='레코드 생성 시각 (기본값으로 현재 시각 사용)',
               existing_nullable=False)
    op.alter_column('captcha_session', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='생성 시각',
               existing_nullable=False)
    op.alter_column('captcha_problem', 'expires_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='문제 교체 시각 (만료일)',
               existing_nullable=False)
    op.alter_column('captcha_problem', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='문제 생성 시각',
               existing_nullable=False)
    op.alter_column('captcha_log', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='문제 생성 시간',
               existing_nullable=False)
    op.alter_column('application', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='삭제 시각 (soft-delete)',
               existing_nullable=True)
    op.alter_column('application', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='수정 시각',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('application', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='생성 시각',
               existing_nullable=False)
    op.alter_column('api_key', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='삭제 시각 (soft-delete)',
               existing_nullable=True)
    op.alter_column('api_key', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='수정 시각',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('api_key', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='생성 시각',
               existing_nullable=False)
    op.alter_column('api_key', 'expires_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='만료 시각 : 0 >= 무제한, 1=1일, 7=7일, 30=30일 등',
               existing_nullable=True)
    # ### end Alembic commands ###
