"""Add difficulty column to ApiKey table

Revision ID: 552c401be985
Revises: 51aeaed07084
Create Date: 2025-09-01 10:28:42.101448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '552c401be985'
down_revision: Union[str, Sequence[str], None] = '51aeaed07084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('difficulty', sa.Enum('LOW', 'MIDDLE', 'HIGH', name='difficulty'), nullable=False, comment='캡챠 난이도'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_key', 'difficulty')
    # ### end Alembic commands ###
