"""Add canceledAt column to payments table

Revision ID: 61e45beac16f
Revises: c9063832e343
Create Date: 2025-09-02 15:59:52.969311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61e45beac16f'
down_revision: Union[str, Sequence[str], None] = 'c9063832e343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True, comment='결제 취소 시간'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'canceled_at')
    # ### end Alembic commands ###
