"""Create contacts table

Revision ID: 75c5931997de
Revises: 85b3dcb1bd35
Create Date: 2025-09-05 09:59:03.278556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c5931997de'
down_revision: Union[str, Sequence[str], None] = 'dff2b5de80c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False, comment='문의 ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='작성자 이름'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='작성자 이메일'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='문의 제목'),
    sa.Column('content', sa.Text(), nullable=False, comment='문의 내용'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성 시각'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
