"""Add ondelete cascade to captcha_log and usage_stats

Revision ID: 83a71340fd40
Revises: 61e45beac16f
Create Date: 2025-09-03 11:22:59.878219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83a71340fd40'
down_revision: Union[str, Sequence[str], None] = '61e45beac16f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('captcha_log_ibfk_1', 'captcha_log', type_='foreignkey')
    op.create_foreign_key(None, 'captcha_log', 'api_key', ['api_key_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('usage_stats_ibfk_1', 'usage_stats', type_='foreignkey')
    op.create_foreign_key(None, 'usage_stats', 'api_key', ['api_key_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usage_stats', type_='foreignkey')
    op.create_foreign_key('usage_stats_ibfk_1', 'usage_stats', 'api_key', ['api_key_id'], ['id'])
    op.drop_constraint(None, 'captcha_log', type_='foreignkey')
    op.create_foreign_key('captcha_log_ibfk_1', 'captcha_log', 'api_key', ['api_key_id'], ['id'])
    # ### end Alembic commands ###
