"""Add ml_confidence and ml_is_bot to captcha_log

Revision ID: 979c61390010
Revises: b1cee9661fbc
Create Date: 2025-09-12 16:37:48.683403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '979c61390010'
down_revision: Union[str, Sequence[str], None] = 'b1cee9661fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('captcha_log', sa.Column('ml_confidence', sa.Float(), nullable=True, comment='머신러닝 모델의 신뢰도 (0.0 ~ 1.0)'))
    op.add_column('captcha_log', sa.Column('ml_is_bot', sa.Boolean(), nullable=True, comment='머신러닝 모델의 봇 판정 (True: 봇, False: 사람)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade schema.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('captcha_log', 'ml_is_bot')
    op.drop_column('captcha_log', 'ml_confidence')
    # ### end Alembic commands ###