"""create payments table

Revision ID: c9063832e343
Revises: 373946e1c8b1
Create Date: 2025-09-02 14:41:57.556524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9063832e343'
down_revision: Union[str, Sequence[str], None] = '373946e1c8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False, comment='결제 고유 식별자 (PK)'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='결제를 요청한 사용자 ID (FK)'),
    sa.Column('payment_key', sa.String(length=255), nullable=False, comment='토스페이먼츠의 결제 고유 키'),
    sa.Column('order_id', sa.String(length=255), nullable=False, comment='가맹점에서 관리하는 주문 ID'),
    sa.Column('order_name', sa.String(length=100), nullable=True, comment='주문 이름 (예: 토스 티셔츠 외 2건)'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='결제 상태 (예: DONE, CANCELED)'),
    sa.Column('method', sa.String(length=50), nullable=True, comment='결제 수단 (예: 카드, 가상계좌)'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='총 결제 금액'),
    sa.Column('currency', sa.String(length=10), nullable=True, comment='통화 (예: KRW)'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='결제 승인 시간'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='레코드 생성 시간'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_key')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
