"""Add originImageUrl to CaptchaProblem

Revision ID: dff2b5de80c2
Revises: f9deeeb96705
Create Date: 2025-09-05 09:23:49.364006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dff2b5de80c2'
down_revision: Union[str, Sequence[str], None] = 'f9deeeb96705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('captcha_problem', sa.Column('origin_image_url', sa.TEXT(), nullable=True, comment='이미지 원본 URL (적합하지 않은 이미지를 걸러내기 위한 용도)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('captcha_problem', 'origin_image_url')
    # ### end Alembic commands ###
