"""Fix timezone for timestamp columns

Revision ID: f9deeeb96705
Revises: 19536121bb8f
Create Date: 2025-09-04 11:26:04.344535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f9deeeb96705'
down_revision: Union[str, Sequence[str], None] = '19536121bb8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='레코드 생성 시간',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='레코드 생성 시간',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
